#!/usr/bin/env python

from subprocess import check_output as run
from urlparse import urlparse

for app in 'nofussbm', 'nofussbm-old':
	conf = run( 'heroku config --app {0} -s'.format( app ), shell = True )
	uri = filter( lambda _ : _.startswith( 'MONGOLAB_URI' ), conf.splitlines() )[ 0 ].split( '=' )[ 1 ]
	parsed = urlparse( uri )
	print run( 'mongodump -u {0.username} -p {0.password} -h {0.hostname}:{0.port} -d {1}'.format( parsed, parsed.path[ 1: ] ), shell = True )
