#!/usr/bin/env python

from os import environ as ENV
from urlparse import urlparse

from pymongo import Connection


MONGOLAB_URI = ENV[ 'MONGOLAB_URI' ]


conn = Connection( MONGOLAB_URI )
db = conn[ urlparse( MONGOLAB_URI ).path[ 1: ] ] 

print 'ACCESS\n' + 80 * '-'
for entry in db[ 'access-logs' ].find():
	print entry['timestamp'].as_datetime(), entry['level'], entry['loggerName'], entry['message']
print 'ERROR\n' + 80 * '-'
for entry in db[ 'error-logs' ].find():
	print entry['timestamp'].as_datetime(), entry['level'], entry['loggerName'], entry['message']
