#!/usr/bin/env python

from os import environ as ENV
from urlparse import urlparse
from sys import argv

from pymongo import Connection


MONGOLAB_URI = ENV[ 'MONGOLAB_URI' ]


conn = Connection( MONGOLAB_URI )
db = conn[ urlparse( MONGOLAB_URI ).path[ 1: ] ] 

if len( argv ) > 1 and argv[ 1 ] == '-e':
	for entry in db[ 'error-logs' ].find():
		print entry['timestamp'].as_datetime(), entry['message']
else:
	for entry in db[ 'access-logs' ].find():
		print entry['message']
