#!/usr/bin/env python

from os import environ
from urlparse import urlparse

up = urlparse( environ['MONGOLAB_URI'] )

cmd = 'mongodump -u {} -p {} -h {}:{} -d {} --out local/dump'.format( up.username, up.password, up.hostname, up.port, up.path[1:] )
print run( cmd, shell = True )
