#!/usr/bin/env python

from os import environ
from urlparse import urlparse

up = urlparse( environ['MONGOLAB_URI'] )

print 'mongo -u {} -p {} {}:{}{}'.format( up.username, up.password, up.hostname, up.port, up.path )
